policies:
  - name: KerasPolicy
    epochs: 1600
    batch_size: 50
    max_training_samples: 300
  - name: FallbackPolicy
    nlu_threshold: 0.3
    # min confidence needed to accept an action prediction from Rasa Core
    core_threshold: 0.3
    # name of the action to be called if the confidence of intent / action
    # is below the threshold
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
